---

-azure_rm_securitygroup:
      resource_group: anotherrg
# Create a security group
- azure_rm_securitygroup:
      resource_group: 'mygroup'
      name: 'mysecgroup'
      purge_rules: 'yes'
      rules:
          - name: 'DenySSH'
            protocol: 'TCP'
            destination_port_range: 22
            access: 'Deny'
            priority: 100
            direction: 'Inbound'
          - name: 'AllowSSH'
            protocol: 'TCP'
            source_address_prefix: '174.109.158.0/24'
            destination_port_range: 22
            access: 'Allow'
            priority: 101
            direction: 'Inbound'

# Update rules on existing security group
- azure_rm_securitygroup:
      resource_group: 'mygroup'
      name: 'mysecgroup'
      rules:
          - name: 'DenySSH'
            protocol: 'TCP'
            destination_port_range: '22-23'
            access: 'Deny'
            priority: 100
            direction: 'Inbound'
          - name: 'AllowSSHFromHome'
            protocol: 'TCP'
            source_address_prefix: '174.109.158.0/24'
            destination_port_range: '22-23'
            access: 'Allow'
            priority: 102
            direction: 'Inbound'
      tags:
          testing: 'testing'
          delete: 'on-exit'

# Delete security group
- azure_rm_securitygroup:
      resource_group: 'mygroup'
      name: 'mysecgroup'
      state: 'absent'
