--- 
- 
  azure_rm_securitygroup: 
    name: mysecgroup
    purge_rules: true
    resource_group: mygroup
    rules: 
      - 
        access: Deny
        destination_port_range: 22
        direction: Inbound
        name: DenySSH
        priority: 100
        protocol: TCP
      - 
        access: Allow
        destination_port_range: 22
        direction: Inbound
        name: AllowSSH
        priority: 101
        protocol: TCP
        source_address_prefix: 174.109.158.0/24
- 
  azure_rm_securitygroup: 
    name: mysecgroup
    resource_group: mygroup
    rules: 
      - 
        access: Deny
        destination_port_range: 22-23
        direction: Inbound
        name: DenySSH
        priority: 100
        protocol: TCP
      - 
        access: Allow
        destination_port_range: 22-23
        direction: Inbound
        name: AllowSSHFromHome
        priority: 102
        protocol: TCP
        source_address_prefix: 174.109.158.0/24
    tags: 
      delete: on-exit
      testing: testing
- 
  azure_rm_securitygroup: 
    name: mysecgroup
    resource_group: mygroup
    state: absent
